// Code generated by goderive DO NOT EDIT.

package set_ttls

// deriveTupleWork returns a function, which returns the input values.
// Since tuples are not first class citizens in Go, this is a way to fake it, because functions that return tuples are first class citizens.
func deriveTupleWork(v0 uint64, v1 []string) func() (uint64, []string) {
	return func() (uint64, []string) {
		return v0, v1
	}
}

// deriveTupleProcessed returns a function, which returns the input values.
// Since tuples are not first class citizens in Go, this is a way to fake it, because functions that return tuples are first class citizens.
func deriveTupleProcessed(v0 uint64, v1 int64) func() (uint64, int64) {
	return func() (uint64, int64) {
		return v0, v1
	}
}
